image: archlinux
packages:
  - asciidoctor
  - rsync
  - openssh
  - ruby-bundler
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - setup: |
      echo "batuu.sevenbyte.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPNMmSHb2ALfwP1oC2oUlVkUTOMR/HooZUbH4YDMQS/k" > $HOME/.ssh/known_hosts

  - build: |
      cd homepage
      bundle install
      ./manage.sh build

  - deploy: |
      cd homepage
      ./manage.sh deploy
