image: archlinux
packages:
  - asciidoctor
  - rsync
  - openssh
  - ruby-bundler
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - build: |
      cd homepage
      bundle install --path vendor/bundle
      ./manage.sh build

  - deploy: |
      cd homepage
      ./manage.sh deploy
