image: archlinux
packages:
  - hugo
  - rsync
  - openssh
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - setup: |
      echo "batuu.sevenbyte.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPNMmSHb2ALfwP1oC2oUlVkUTOMR/HooZUbH4YDMQS/k" > $HOME/.ssh/known_hosts

  - build: |
      cd homepage
      hugo

  - deploy: |
      cd homepage
      rsync -e "ssh -o VerifyHostKeyDNS=yes -o StrictHostKeyChecking=accept-new" -rP --delete "public/" deploy@batuu.sevenbyte.org:rumpelsepp.org/
