image: archlinux
packages:
  - hugo
  - rsync
  - openssh
secrets:
  - 0d06436c-bc8f-4f65-af13-cad62d4f1127

tasks:
  - setup: |
      echo "tatooine.sevenbyte.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF0o+5NqGQ4c/2rwaKZ1n3/HrO8H7DL3PaB8xyyFm428" > $HOME/.ssh/known_hosts
      echo "tatooine.sevenbyte.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBp06nDZHbCkbM96iKtmvHGDLafaX/PQ/Meed7nn9tR2f/QQk37nSEcI6xXNUBJGbw5/+u+PHlWYlZzwaG+Ewn8=" > $HOME/.ssh/known_hosts

  - build: |
      cd homepage
      hugo

  - deploy: |
      cd homepage
      rsync -e "ssh -o VerifyHostKeyDNS=yes -o StrictHostKeyChecking=accept-new" -rP --delete "public/" deploy@tatooine.sevenbyte.org:rumpelsepp.org/
