language: ruby
cache: bundler
rvm:
- 2.5.0

sudo: false

script: JEKYLL_ENV=production bundle exec jekyll build

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: _site
  repo: rumpelsepp/rumpelsepp.github.io
  target_branch: master
  on:
    branch: master
