pipeline:
  setup:
    image: archlinux:latest
    commands:
      - pacman -Syu --noconfirm
      - pacman -S --noconfirm hugo rsync openssh git
      - mkdir -p "$HOME/.ssh"
      - echo "tatooine.sevenbyte.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIF0o+5NqGQ4c/2rwaKZ1n3/HrO8H7DL3PaB8xyyFm428" > "$HOME/.ssh/known_hosts"
      - echo "tatooine.sevenbyte.org ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBp06nDZHbCkbM96iKtmvHGDLafaX/PQ/Meed7nn9tR2f/QQk37nSEcI6xXNUBJGbw5/+u+PHlWYlZzwaG+Ewn8=" > "$HOME/.ssh/known_hosts"
      - echo "$SSH_PRIVKEY" > "$HOME/.ssh/id_ed25519"
      - chmod 0600 "$HOME/.ssh/id_ed25519"

      - hugo

      - rsync -e "ssh -o VerifyHostKeyDNS=yes -o StrictHostKeyChecking=accept-new" -rP --delete "public/" deploy@tatooine.sevenbyte.org:rumpelsepp.org/
    secrets: [ ssh_privkey ]
