# Site settings
title: ~rumpelsepp
email: stefan@rumpelsepp.org
description: I break stuff
url: "https://rumpelsepp.org" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/

timezone: Europe/Berlin
paginate: 5

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
    #   author: "Stefan Tatschner"

collections:
  stuff:
    output: true

# Build settings
plugins:
    - jekyll-asciidoc
    - jekyll-feed

asciidoctor:
  attributes:
    - source-highlighter=pygments
    - pygments-style=default
    - stylesdir=/assets/css
    - imagesdir=/assets/img
    - prewrap!

exclude:
  - vendor
  - manage.sh
  - Gemfile
  - Gemfile.lock
