# Site settings
title: ~rumpelsepp/brain
email: rumpelsepp@sevenbyte.org
description: Random bits from deep inside my brain
url: "https://rumpelsepp.github.io" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
github_username:  rumpelsepp

timezone: Europe/Berlin

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
    #   author: "Stefan Tatschner"

# Build settings
plugins:
    - jekyll-asciidoc
    - jekyll-feed

asciidoctor:
  attributes:
    - icons=font
    - source-highlighter=highlight.js
    - imagesdir=/assets/img
    - prewrap!

exclude:
  - vendor
  - manage.sh
  - Gemfile
  - Gemfile.lock
