baseURL = "https://rumpelsepp.org/"
languageCode = "en-us"
title = "~rumpelsepp"
pygmentsUseClasses = true
enableGitInfo = true

[frontmatter]
date  = [":filename", ":default"]

[markup.goldmark.renderer]
unsafe = true
