= Contact

Hi, I'm Stefan. I like to mess with Linux, network security, and free
software. You may find me in the web as `rumpelsepp`, or on:

* Matrix: @rumpelsepp:hackbrettl.de,
* https://git.sr.ht./~rumpelsepp[sourcehut],
* https://github.com/rumpelsepp[github], or
* https://mastodon.social/@rumpelsepp[Mastodon].

Over the years I experimented a lot with mail servers and DNS, so there are a few email addresses lurking around in the internet:

* stefan.tatschner@gmail.com (please don't use this)
* rumpelsepp@sevenbyte.org
* stefan@sevenbyte.org
* stefan@rumpelsepp.org (<- I use this as my PGP identity)

Everything is collected in a single mailbox, so it doesn't matter which one you choose.
The more important thing is to use my GPG key to ensure end-to-end security.

The reason why I have four mail addresses is: once upon a time I started with gmail.
Then, my first mail server came and I didn't havea domain.
In a session with a friend the domain sevenbyte.org popped up; but I didn't really like it, since it had no meaning at all.
But I used it for everything in my infrastructure.
Subsequently, my own DNS servers came and I wanted to make a clean cut in ordner to move my own DNS with enabled DNSSEC.
Well, the mail addresses will stay, since they are already there.
We will see what kind of stuff will join my pool…

== GPG Keys

My GPG key is available via https://datatracker.ietf.org/doc/draft-koch-openpgp-webkey-service/[WKD].

----
$ gpg --locate-key stefan@rumpelsepp.org
----
