name: GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: shalzz/zola-deploy-action@v0.16.1
        env:
          BUILD_DIR: public
          BUILD_ONLY: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # BUILD_FLAGS: --drafts

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Deploy
        run: |
          rsync -e "ssh" -rP --delete "public/" deploy@tatooine.sevenbyte.org:rumpelsepp.org/

